/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_star8green;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Patrick Dale
 */
public class Single_journey extends javax.swing.JPanel {

    /**
     * Creates new form Single_journey
     */
    public Single_journey() {
        initComponents();
        getDestFare();
        reciept_panel.setVisible(false);
        fare_label.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destination_comboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        recievedCash_textField = new javax.swing.JTextField();
        reciept_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        recievedCash_label = new javax.swing.JLabel();
        change_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        total_label = new javax.swing.JLabel();
        cancel_button = new javax.swing.JButton();
        confirm_button = new javax.swing.JButton();
        ok_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fare_label = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(983, 578));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 90, 43));
        jLabel1.setText("SINGLE JOURNEY");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 52, 52));
        jLabel2.setText("Select Destination:");

        destination_comboBox.setBackground(new java.awt.Color(255, 255, 255));
        destination_comboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        destination_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destination 1", "Destination 2", "Destination 3", "Destination 4", "Destination 5", "Destination 6" }));
        destination_comboBox.setBorder(null);
        destination_comboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                destination_comboBoxItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 52, 52));
        jLabel3.setText("Recieved Cash:");
        jLabel3.setToolTipText("");

        recievedCash_textField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recievedCash_textField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        reciept_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 52, 52));
        jLabel5.setText("Total:");

        recievedCash_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        recievedCash_label.setForeground(new java.awt.Color(52, 52, 52));
        recievedCash_label.setText("100.00");

        change_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        change_label.setForeground(new java.awt.Color(52, 52, 52));
        change_label.setText("30.00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(52, 52, 52));
        jLabel8.setText("Recieved Cash:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(52, 52, 52));
        jLabel9.setText("Change:");

        total_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total_label.setForeground(new java.awt.Color(52, 52, 52));
        total_label.setText("70.00");

        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_cancel_button.PNG"))); // NOI18N
        cancel_button.setBorder(null);
        cancel_button.setBorderPainted(false);
        cancel_button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_cancel_button_click.PNG"))); // NOI18N
        cancel_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_cancel_button_hover.PNG"))); // NOI18N
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        confirm_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_confirml_button.PNG"))); // NOI18N
        confirm_button.setBorder(null);
        confirm_button.setBorderPainted(false);
        confirm_button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_confirml_button_click.PNG"))); // NOI18N
        confirm_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_confirml_button_hover.PNG"))); // NOI18N
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reciept_panelLayout = new javax.swing.GroupLayout(reciept_panel);
        reciept_panel.setLayout(reciept_panelLayout);
        reciept_panelLayout.setHorizontalGroup(
            reciept_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reciept_panelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(reciept_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reciept_panelLayout.createSequentialGroup()
                        .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reciept_panelLayout.createSequentialGroup()
                        .addGroup(reciept_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(reciept_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total_label)
                            .addComponent(recievedCash_label)
                            .addComponent(change_label))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        reciept_panelLayout.setVerticalGroup(
            reciept_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reciept_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(reciept_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reciept_panelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reciept_panelLayout.createSequentialGroup()
                        .addComponent(total_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recievedCash_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(change_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(reciept_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ok_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_ok_button.PNG"))); // NOI18N
        ok_button.setBorder(null);
        ok_button.setBorderPainted(false);
        ok_button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_ok_button_click.PNG"))); // NOI18N
        ok_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/single_journey_ok_button_hover.PNG"))); // NOI18N
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 52, 52));
        jLabel6.setText("Fare:");

        fare_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fare_label.setForeground(new java.awt.Color(52, 52, 52));
        fare_label.setText("70.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(destination_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel6)
                .addGap(239, 239, 239)
                .addComponent(fare_label))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(recievedCash_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(ok_button))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(reciept_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fare_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recievedCash_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(ok_button)
                .addGap(53, 53, 53)
                .addComponent(reciept_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getDestFare(){
        arrDestFare[0][0]="Destination 1";arrDestFare[0][1]="15.00";
        arrDestFare[1][0]="Destination 1";arrDestFare[1][1]="15.00";
        arrDestFare[2][0]="Destination 1";arrDestFare[2][1]="20.00";
        arrDestFare[3][0]="Destination 1";arrDestFare[3][1]="20.00";
        arrDestFare[4][0]="Destination 1";arrDestFare[4][1]="25.00";
        arrDestFare[5][0]="Destination 1";arrDestFare[5][1]="30.00";
    }
    
    
    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        boolean isError=false;
        float recieved_cash=0;
        float total;
        if(recievedCash_textField.getText().isEmpty()){
            isError=true;
            JOptionPane.showMessageDialog(this, "Please enter recieved cash.","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            try{
            recieved_cash = Float.parseFloat(recievedCash_textField.getText());
            }catch(NumberFormatException e){
                isError=true;
                JOptionPane.showMessageDialog(this, "Please enter cash value only.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
        if(!isError){
            total=Float.parseFloat(arrDestFare[destination_comboBox.getSelectedIndex()][1]);
            float change=recieved_cash-total;
            total_label.setText(""+total);
            recievedCash_label.setText(""+recieved_cash);
            change_label.setText(""+change);
            destination_comboBox.setEnabled(false);
            recievedCash_textField.setEnabled(false);
            ok_button.setEnabled(false);
            reciept_panel.setVisible(true);
        }
    }//GEN-LAST:event_ok_buttonActionPerformed

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed
        reciept_panel.setVisible(false);
        recievedCash_textField.setText("");
        destination_comboBox.setSelectedIndex(0);
        fare_label.setText("");
        recievedCash_textField.setEnabled(true);
        ok_button.setEnabled(true);
    }//GEN-LAST:event_confirm_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        reciept_panel.setVisible(false);
        destination_comboBox.setEnabled(true);
        recievedCash_textField.setEnabled(true);
        ok_button.setEnabled(true);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void destination_comboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_destination_comboBoxItemStateChanged
        fare_label.setText(arrDestFare[destination_comboBox.getSelectedIndex()][1]);
    }//GEN-LAST:event_destination_comboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel change_label;
    private javax.swing.JButton confirm_button;
    private javax.swing.JComboBox<String> destination_comboBox;
    private javax.swing.JLabel fare_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton ok_button;
    private javax.swing.JPanel reciept_panel;
    private javax.swing.JLabel recievedCash_label;
    private javax.swing.JTextField recievedCash_textField;
    private javax.swing.JLabel total_label;
    // End of variables declaration//GEN-END:variables
    String[][] arrDestFare = new String[6][2];
}
